version: '3.8'

services:
  recommender:
    build: .
    image: restaurant-recommender:latest
    container_name: restaurant-container
    ports:
      - "5000:5000"   # Flask default port
    volumes:
      - .:/app
    environment:
      - PYTHONUNBUFFERED=1
      - FLASK_APP=app.py     # Make sure your main Flask app file is app.py, else change accordingly
    command: ["flask", "run", "--host=0.0.0.0", "--port=5000"]
    networks:
      - recommender-network

networks:
  recommender-network:
    driver: bridge
