version: '3.8'

services:
  recommender:
    build: . 
    image: restaurant-recommender:latest
    container_name: restaurant-container
    ports:
      - "8888:8888"  # For Jupyter Notebook (optional)
    volumes:
      - .:/app  
    environment:
      - PYTHONUNBUFFERED=1
    command: ["jupyter", "notebook", "--ip=0.0.0.0", "--port=8888", "--no-browser", "--allow-root", "--NotebookApp.token=''"]  # Uncomment for Jupyter
    networks:
      - recommender-network

networks:
  recommender-network:
    driver: bridge