version: '3.8'

services:
  recommender:
    build: .
    image: restaurant-recommender:latest
    container_name: restaurant-container
    ports:
      - "5000:5000"   
    volumes:
      - .:/app        
    environment:
      - PYTHONUNBUFFERED=1
      - FLASK_APP=app.py      
      - FLASK_ENV=development 
    command: flask run --host=0.0.0.0 --port=5000
    networks:
      - recommender-network

networks:
  recommender-network:
    driver: bridge

