pipeline {
    agent any

    environment {
        REPO_URL = 'https://github.com/051821/Recommender-sys.git'
        BRANCH = 'main'
        APP_DIR = 'Recommender-sys'  // Adjust if needed
    }

    stages {
        stage('Clone Repository') {
            steps {
                git branch: "${BRANCH}", url: "${REPO_URL}"
            }
        }

        stage('Build Docker Containers') {
            steps {
                dir("${APP_DIR}") {
                    bat 'docker-compose build'
                }
            }
        }

        stage('Run Containers') {
            steps {
                dir("${APP_DIR}") {
                    bat 'docker-compose up -d'
                }
            }
        }

        stage('Verify Containers') {
            steps {
                bat 'docker ps'
            }
        }
    }

    post {
        always {
            echo 'Cleaning up Docker containers...'
            dir("${APP_DIR}") {
                bat 'docker-compose down -v'
            }
            cleanWs()
        }
    }
}
